version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - curl -s https://getcomposer.org/installer | php
  build:
    commands:
      - echo Build started on `date`
      - npm run lint
  post_build:
    commands:
      - echo Build completed on `date`
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no